### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jjjermiah** [bhklab/med-imagetools#139]
- [ ] TODOs
    - [x] `cli/dicomsort.py` # TODO:  figure out if patterned path i.e data/%PatientID can be a pathlib.Path
    - [x] `cli/dicomsort.py` # TODO: eagerly validate target pattern somehow?
    - [x] `dicom/sort/dicomsorter.py` # TODO: keep this logic, but make the suggestion more
